### PR TITLE
Update Swate template contribution guide

### PR DESCRIPTION
**Pull request by StellaEggels**
Updated the Swate template contribution guide for use of Swate alpha and to update best practices.
@Freymaurer @Brilator 

Currently the swate template contribution guide can be found under “expert features” on the knowledge base. Since there is no expert mode in swate alpha, it should be listed directly under Swate manual. Can you change this?

### CODE REVIEW

**Comment by Brilator** [comment]
> with an extension template that contains ONLY the optional/recommended information

Why the "only"? Would it harm to have the mandatory in there as well? If users add the mandatory first and then the extension, only those missing terms would be added anyways.

**Comment by Brilator** [comment]
> Currently the swate template contribution guide can be found under “expert features” on the knowledge base. Since there is no expert mode in swate alpha, it should be listed directly under Swate manual. Can you change this?

True, but I guess the templating is still a bit more "expert" than other swate features. The guide is also linked twice in the sidebar (one additional time under guides -> contribute). Feel free to adapt the sidebar `src/docs/_sidebars/mainSidebar.md` to your needs. 

I guess the overall swate manual (and knowledge base) will need an overhaul soon.

**Review by Brilator — APPROVED** [review]

**Comment by StellaEggels** [comment]
> > with an extension template that contains ONLY the optional/recommended information
> 
> Why the "only"? Would it harm to have the mandatory in there as well? If users add the mandatory first and then the extension, only those missing terms would be added anyways.

Having the mandatory information as well would also be fine with me. When we discussed that we should avoid redundancy in templates I understood that it would be better not to duplicate the mandatory information, but I also see the benefit of having all information in one template. Should I change it?

**Comment by Brilator** [comment]
It's up to you. Sorry, I missed what we discussed. With one option the user needs to add two templates, with the other we need to maintain redundant templates.

**Comment by StellaEggels** [comment]
Then I would keep it as it is for now. If we see that it is inconvenient, we can still change it. Can you please merge it? I don’t have the rights.

**Comment by Brilator** [comment]
Sorry, I thought once it's approved, you can merge.

**Pull request merged**
