### PR TITLE
add Ontology Service Landscape article 

### PR DESCRIPTION
**Pull request by StellaEggels**
## Description
We added an article describing the ontologies included in the SwateDB and how to use and contribute to them.

### CODE REVIEW

**Comment by Brilator** [comment]
Cool! 

I would suggest to remove the bold formatting from headlines. This disturbs the TOC. 

Screenshot 2023-11-21 at 11 21 04

And please double-check the table. I can see it displayed properly in vscode preview, but apparently fornax does not like it. 

Screenshot 2023-11-21 at 11 21 26

**Comment by Brilator** [comment]
You can also check the rendering locally. Explained here:  https://nfdi4plants.org/nfdi4plants.knowledgebase/docs/CONTRIBUTING.html

**Comment by StellaEggels** [comment]
@Brilator please check formally

**Comment by Brilator** [comment]
Looks good from my side. 

Just two things: 
1. the image resolution seems low
2. Do me a favor and list the images in the image index src/docs/image-index.md

**Pull request merged**
