### PR TITLE
Update arc_installation_macos.md

### PR DESCRIPTION
**Pull request by Brilator**
Do you have a macOS with intel processor and can check whether the installation works? @Mestizia 

Related to https://github.com/nfdi4plants/ARCCommander/issues/246

### CODE REVIEW

**Comment by Mestizia** [comment]
No I do not. Nor I have access to one at the moment
image

**Comment by Brilator** [comment]
Which release did you download to get the "bad CPU"? Your x86_64 is an AMD?

**Comment by Mestizia** [comment]
I downloaded the arc_osx-arm64.
I have an intel CPU [2,3 GHz Quad-Core Intel Core i7] x86_64. I know it's not compatible with the one that you linked. 

Is a user using the arm64 having trouble installing and running arc commander?

**Comment by Brilator** [comment]
Yes. I have an arm64, I can use the arc_osx-x64, but not the other one.

**Pull request merged**
