### PR TITLE
Readme, Contribution and License

### PR DESCRIPTION
**Pull request by Brilator**
1. Moved readme parts on "development" to the src/docs/CONTRIBUTING.md guide. 
2. Added description to readme
3. Changed license from MIT © @Freymaurer to CC-BY4.0.

Last point likely requires better referencing to the backend (web-components) and fornax.

### CODE REVIEW

**Review by andreaschrader — COMMENTED** [review]
1) Moved readme parts on "development" to the src/docs/CONTRIBUTING.md guide.

These parts were correctly integrated. Moving implies removing at the other location. If this is intented repo initiators are better suited to decide if this is ok.

2) Added description to readme

Despite the license part, I can approve this part. A bit more description on the README.md page as compared to the current version is usefull. If the development section can be moved and thereby removed here or only duplicated needs to be judged by those setting up the repo/website (@Freymaurer?)

3) Changed license from MIT © @Freymaurer to CC-BY4.0.

This has a broader impact and I assumes the other previous contributors should agree. Also consider those contributions integrated from the documentation e.g. of the arcCommander and Swate. Likely, this is also a decision at higher level as well as and also at a level apart from the context as mentioned in the pull request already (fornax etc.). Therefore, I can not approve on this here.

**Comment by Brilator** [comment]
Agreed, you are not a suitable reviewer on this PR. Just wanted to let you know. 
Needs to be decided at DP. Linked the PR in another issue as well.

**Review by Freymaurer — APPROVED** [review]

**Comment by Freymaurer** [comment]
I didn't decide on the MIT license and i cannot tell if the new license is a better fit or not. All other changes look good to me.

**Review by Martin-Kuhl — APPROVED** [review]
Checked the licensing for figures again. 
Everything is under creative commons, so CC-BY4.0 looks good to me.

**Pull request merged**
