### PR TITLE
Add knowledge base article about ontologies

### PR DESCRIPTION
**Pull request by Hannah-Doerpholz**
We have worked on writing a general article concerning ontologies for the DataPLANT community. It was co-written by @Hannah-Doerpholz , @AngelaKranz and @kdumschott and is now ready for publishing. Since only a small amount of new content will be added, no prior local testing was performed.

### CODE REVIEW

**Comment by Brilator** [comment]
Great! We've collected a few "rules" for working on the teaching materials repo (and I think the same ones are planned to apply here as well, but need to be added to the contribution guide)

https://github.com/nfdi4plants/teaching_materials#repository-rules-for-collaborators

In summary: Feel free to assign one or two reviewer(s). Once the PR is approved by at least one reviewer, you can merge it.

**Comment by Hannah-Doerpholz** [comment]
Thank you for that information @Brilator . However, I don't know how to assign a reviewer (I am also not super familiar with GitHub, but I'm working on it). The information I found on that said that I need to have write access in order to be able to assign a reviewer (and also for merging), which I don't think I have.

**Comment by Hannah-Doerpholz** [comment]
I added new information and examples where you suggested them and also reformatted the table a few times to try and get it to look nice. Now, everything should be correct.

**Comment by Martin-Kuhl** [comment]
Looks good to me. One last question: What about the remaining OBO Foundry principles between 12 and 20?

**Comment by Hannah-Doerpholz** [comment]
Unfortunately they don't say anything about that on their website. The explicitly list 1-12, 16 and 20, but nothing in between. We decided to stick to the OBO Foundry numbering, but we are aware that it might seem confusing.

**Pull request merged**
